name: For Subscribed And Demo Reports
on:
 workflow_dispatch:
  inputs:
   ref:
    default: 'main'
 repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print custom payload data
        run: |
          echo "Received event type: ${{ github.event.action }}"
          echo "Client payload data: ${{ github.event.client_payload.some_data }}"
